name: ceph-csi

on:
  push:
    paths:
      - '.github/workflows/ceph-csi.yml'
      - 'build/ceph-csi/**'
      - '!build/ceph-csi/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/ceph-csi/.version)
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # We need Docker, but not the Docker buildx bits?
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Repushing is necessary because a Docker manifest references images
      # and those images have to exist in the registry beforehand.
      - name: Pull, retag, and repush amd64 image
        run: |
          docker pull quay.io/cephcsi/cephcsi:v${{ env.VERSION }}
          docker tag quay.io/cephcsi/cephcsi:v${{ env.VERSION }} raspbernetes/ceph-csi:v${{ env.VERSION }}-amd64
          docker push raspbernetes/ceph-csi:v${{ env.VERSION }}-amd64

      - name: Pull, retag, and repush arm64 image
        run: |
          docker pull quay.io/cephcsi/cephcsi:v${{ env.VERSION }}-arm64
          docker tag quay.io/cephcsi/cephcsi:v${{ env.VERSION }}-arm64 raspbernetes/ceph-csi:v${{ env.VERSION }}-arm64
          docker push raspbernetes/ceph-csi:v${{ env.VERSION }}-arm64

      - name: Build Multiarch Manifest
        if: github.ref == 'refs/heads/master'
        run: |
          docker manifest create raspbernetes/ceph-csi:v${{ env.VERSION }} raspbernetes/ceph-csi:v${{ env.VERSION }}-amd64 raspbernetes/ceph-csi:v${{ env.VERSION }}-arm64
          docker manifest annotate --arch arm64 raspbernetes/ceph-csi:v${{ env.VERSION }} raspbernetes/ceph-csi:v${{ env.VERSION }}-arm64
          docker manifest push raspbernetes/ceph-csi:v${{ env.VERSION }}
