name: curl

on:
  push:
    paths:
      - '.github/workflows/curl.yml'
      - 'build/curl/**'
      - '!build/curl/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Clone Repository
        run: |
          git clone https://github.com/curl/curl-docker.git
          cd curl-docker
          make setup

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag raspbernetes/curl:${{ github.sha }} \
            -f ./curl-docker/alpine/latest/Dockerfile \
            ./curl-docker/alpine/latest/ \
            --push

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag raspbernetes/curl:latest \
            --tag raspbernetes/curl:${{ LATEST_RELEASE_VERSION }} \
            --tag k8sathome/curl:${{ LATEST_RELEASE_VERSION }} \
            -f ./curl-docker/alpine/latest/Dockerfile \
            ./curl-docker/alpine/latest/ \
            --push
