name: hubble-ui

on:
  push:
    paths:
      - '.github/workflows/hubble-ui.yml'
      - 'build/hubble-ui/**'
      - '!build/hubble-ui/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Prepare
        id: prep
        run: |
          BASE_DIR=build/hubble-ui
          VERSION=$(cat ${BASE_DIR}/.version)
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=base_dir::${BASE_DIR}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: hubble-ui frontend - Build and Push
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: ${{ steps.prep.outputs.base_dir }}/
          file: ${{ steps.prep.outputs.base_dir }}/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            raspbernetes/hubble-ui:${{ github.sha }}

      - name: hubble-ui frontend -  Build and Push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: ${{ steps.prep.outputs.base_dir }}/
          file: ${{ steps.prep.outputs.base_dir }}/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            raspbernetes/hubble-ui:latest
            raspbernetes/hubble-ui:${{ steps.prep.outputs.version }}

      - name: hubble-ui backend - Build and Push
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: ${{ steps.prep.outputs.base_dir }}/backend/
          file: ${{ steps.prep.outputs.base_dir }}/backend/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            raspbernetes/hubble-ui-backend:${{ github.sha }}

      - name: hubble-ui backend -  Build and Push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: ${{ steps.prep.outputs.base_dir }}/backend/
          file: ${{ steps.prep.outputs.base_dir }}/backend/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            raspbernetes/hubble-ui-backend:latest
            raspbernetes/hubble-ui-backend:${{ steps.prep.outputs.version }}
