name: istio-envoy

on:
  push:
    paths:
      - '.github/workflows/istio-envoy.yml'
      - 'build/istio-envoy/**'
      - '!build/istio-envoy/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1800
    env:
      VERSION: $(cat build/istio-envoy/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/istio-envoy:${{ github.sha }} \
            -f ./build/istio-envoy/Dockerfile \
            ./build/istio-envoy/ \
            --push

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/istio-envoy:latest \
            --tag raspbernetes/istio-envoy:${{ env.VERSION }} \
            -f ./build/istio-envoy/Dockerfile \
            ./build/istio-envoy/ \
            --push
