name: kustomize

on:
  push:
    paths:
      - 'build/kustomize/**'
      - '!build/kustomize/*.md'
  pull_request:
    paths:
      - 'build/kustomize/**'
      - '!build/kustomize/*.md'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/kustomize/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag raspbernetes/kustomize:${{ github.sha }} \
            -f ./build/kustomize/Dockerfile \
            --push ./build/kustomize/

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
<<<<<<< HEAD
            --tag raspbernetes/kustomize:latest \
=======
>>>>>>> 26f6c1a99c8fb91410f7941af03b1590d3bebdd7
            --tag raspbernetes/kustomize:${{ env.VERSION }} \
            --tag k8sathome/kustomize:${{ env.VERSION }} \
            -f ./build/kustomize/Dockerfile \
            --push ./build/kustomize/
